import { createTheme } from "office-ui-fabric-react";
export const BASE_THEME = createTheme({
    palette: {
      themePrimary: '#4d1cff',
      themeLighterAlt: '#f8f6ff',
      themeLighter: '#e3dbff',
      themeLight: '#cabbff',
      themeTertiary: '#9477ff',
      themeSecondary: '#6337ff',
      themeDarkAlt: '#4619e6',
      themeDark: '#3b15c2',
      themeDarker: '#2b108f',
      neutralLighterAlt: '#ebe7f8',
      neutralLighter: '#e7e3f4',
      neutralLight: '#dddaea',
      neutralQuaternaryAlt: '#cecbda',
      neutralQuaternary: '#c5c2d0',
      neutralTertiaryAlt: '#bdbac8',
      neutralTertiary: '#595959',
      neutralSecondary: '#373737',
      neutralPrimaryAlt: '#2f2f2f',
      neutralPrimary: '#000000',
      neutralDark: '#151515',
      black: '#0b0b0b',
      white: '#f1edff',
    }});